name: stock_notes
description: "Stock Notes"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.8
  get: ^4.6.6 #路由/状态插件
  dio: ^5.7.0
  visibility_detector: ^0.4.0+2

  convert: ^3.1.2
  intl: ^0.19.0  # 格式化日期
  crypto: ^3.0.6  # 生成 MD5
  encrypt: ^5.0.3
  connectivity_plus: ^6.1.1

  #UI
  flutter_screenutil: ^5.9.3
  flutter_smart_dialog: ^4.9.8+5
  flutter_inappwebview: ^6.1.5
  flutter_slidable: ^3.1.2 #cell滑动事件
  photo_view: ^0.15.0 #图片预览
  #图片预览与保存 https://juejin.cn/post/7295654213618073615?searchId=2024092915095437248644A536B2AA155A

  #存储
  shared_preferences: ^2.3.3
  get_storage: ^2.1.1
  #  isar: ^3.1.0+1

  #原生相关
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3
  #  image_gallery_saver: ^2.0.3
  #  image_picker: ^1.1.2
  #  share_plus: ^9.0.0
  #  permission_handler: ^11.3.1
  package_info_plus: ^8.1.2
  device_info_plus: ^11.2.0
  url_launcher: ^6.3.1

  # 如果需要使用国际化，请添加以下依赖
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
