name: Flutter Release APK

trigger:
  push:
    tags:
      - 'v*'

jobs:
  build_apk:
    steps:
      - uses: actions/checkout@v1
      - name: 安装 Flutter
        run: |
          git clone https://gitee.com/mirrors/flutter.git
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter doctor
      - name: 构建 APK
        run: |
          flutter pub get
          flutter build apk --release
      - name: 上传到 Gitee Release
        run: |
          curl -X POST "https://gitee.com/api/v5/repos/wscqs/stock_notes/releases" \
            -H "Content-Type: application/json" \
            -H "Authorization: token 5f3aeeece53cd20e902f2b2c83603a97" \
            -d '{
              "tag_name": "${CI_COMMIT_TAG}",
              "name": "${CI_COMMIT_TAG}",
              "body": "自动发包",
              "draft": false,
              "prerelease": false
            }'

          curl -X POST "https://gitee.com/api/v5/repos/wscqs/stock_notes/releases/assets?access_token=$GITEE_TOKEN&tag_name=${CI_COMMIT_TAG}" \
            -F "name=app-release.apk" \
            -F "attachment=@build/app/outputs/flutter-apk/app-release.apk"
