name: Flutter Build

on:
  release:
    types: [published]  # 只在发布 Release 时运行

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Flutter pub get
        run: flutter pub get

      # Build Android APK
      - name: Build Android APK
        run: flutter build apk --release

      # Build macOS app
      - name: Build macOS App
        run: flutter build macos --release

      # Zip macOS .app for distribution
      - name: Zip macOS App
        run: |
          cd build/macos/Build/Products/Release
          ditto -c -k --sequesterRsrc --keepParent *.app macos-app.zip

      # Upload Android APK
      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # Upload macOS .app
      - name: Upload macOS App (.app)
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: build/macos/Build/Products/Release/*.app

      # Upload macOS zip
      - name: Upload macOS Zip (.zip)
        uses: actions/upload-artifact@v4
        with:
          name: macos-app-zip
          path: build/macos/Build/Products/Release/macos-app.zip
