name: Flutter Release Build (macOS with ZIP)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build macOS App
        run: flutter build macos --release

      - name: Zip .app into macos-app.zip
        run: |
          cd build/macos/Build/Products/Release
          ditto -c -k --sequesterRsrc --keepParent *.app macos-app.zip

      - name: Upload .app (for inspection or manual use)
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: build/macos/Build/Products/Release/*.app

      - name: Upload .zip (for distribution)
        uses: actions/upload-artifact@v4
        with:
          name: macos-app-zip
          path: build/macos/Build/Products/Release/macos-app.zip
