name: Flutter Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Build macOS
        run: flutter build macos --release

      - name: Upload Android APK
        uses: actions/upload-artifact@v3.1.3
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload macOS App
        uses: actions/upload-artifact@v3.1.3
        with:
          name: macos-app
          path: build/macos/Build/Products/Release/*.app
