name: Flutter Multi-Platform Release

on:
  release:
    types: [published]

jobs:
  build_android_macOS:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'

      - name: Clean Flutter pub
        run: flutter clean
        
      - name: Flutter pub get
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Clean macOS CocoaPods
        run: |
          cd macos
          rm -rf Pods Podfile.lock
          pod repo update
          pod install
          cd ..

      - name: Build macOS App
        run: flutter build macos --release

      - name: Zip macOS App
        run: |
          cd build/macos/Build/Products/Release
          ditto -c -k --sequesterRsrc --keepParent *.app macos-stocknote.zip
          mv macos-stocknote.zip ${{ github.workspace }}

      - name: Upload APK & macOS zip to GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ github.workspace }}/build/app/outputs/apk/release/app-release.apk
            ${{ github.workspace }}/macos-stocknote.zip

  build_windows:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'

      - name: Clean Flutter pub
        run: flutter clean
        
      - name: Flutter pub get
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows --release

      - name: Zip Windows App
        run: |
          cd build/windows/x64/runner/Release
          powershell -Command "Compress-Archive -Path * -DestinationPath windows-stocknote.zip"
          mv windows-stocknote.zip ${{ github.workspace }}

      - name: Upload Windows zip to GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ github.workspace }}/windows-stocknote.zip
