name: Flutter Multi-Platform Release

on:
  release:
    types: [published]

jobs:
  build_macos_android:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build macOS App
        run: flutter build macos --release

      - name: Zip macOS App
        run: |
          cd build/macos/Build/Products/Release
          ditto -c -k --sequesterRsrc --keepParent *.app macos-app.zip
          mv macos-app.zip ${{ github.workspace }}

      - name: Upload APK & macOS zip to GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ github.workspace }}/build/app/outputs/apk/release/app-release.apk
            ${{ github.workspace }}/macos-app.zip
