name: Flutter Multi-Platform Release

on:
  release:
    types: [published]

jobs:
 build_windows:
   runs-on: windows-latest

   steps:
     - uses: actions/checkout@v3

     - uses: subosito/flutter-action@v2
       with:
         flutter-version: '3.29.2'

     - name: Flutter pub get
       run: flutter pub get

     - name: Build Windows App
       run: flutter build windows --release

     - name: Zip Windows App
       run: |
          cd build/windows/x64/runner/Release
          powershell -Command "Compress-Archive -Path * -DestinationPath windows-app.zip"
          mv windows-app.zip ${{ github.workspace }}
         

     - name: Upload Windows zip to GitHub Release
       uses: softprops/action-gh-release@v2
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         files: ${{ github.workspace }}/windows-app.zip
       


